todoapp/app/models.py
from . import db
from flask_login import UserMixin
from datetime import datetime
import pytz

class User(UserMixin,db.Model):
	id=db.Column(db.Integer,primary_key=True)
	username=db.Column(db.String(50),nullable=False)
	password=db.Column(db.String(128),nullable=False)

class Task(db.Model):
	id=db.Column(db.Integer,primary_key=True)
	taskname=db.Column(db.String(100),nullable=False)
	created_at=db.Column(db.DateTime,default=datetime.now(pytz.timezone('Asia/Tokyo')))
	due_date=db.Column(db.DateTime)

todoapp/app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField,DateField
from wtforms.validators import DataRequired,EqualTo

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password1 = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password1')])
    submit = SubmitField('Sign Up')

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')


class TaskForm(FlaskForm):
	taskname=StringField('Task',validators=[DataRequired()])
	due_date=DateField('Due Date')
	submit=SubmitField('Submit')

todoapp/app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy 
from flask_login import LoginManager

db= SQLAlchemy()
login_manager=LoginManager()
login_manager.ligin_view='auth.login'

def create_app():
	app=Flask(__name__,instance_relative_config=True)
	app.config.from_pyfile('config.py')

	db.init_app(app)
	login_manager.init_app(app)

	with app.app_context():
		from .routes import auth_bp,index_bp,task_bp
		app.register_blueprint(auth_bp)
		app.register_blueprint(index_bp)
		app.register_blueprint(task_bp)

		db.create_all()
	return app

@login_manager.user_loader
def load_user(user_id):
	from .models import User
	return User.query.get(int(user_id))

todoapp/app/routes.py
from flask import Blueprint, render_template,url_for,request,redirect,flash
from flask_login import login_user,logout_user,login_required, current_user
from . import db
from .models import User,Task
from .forms import RegistrationForm,LoginForm,TaskForm
from werkzeug.security import check_password_hash, generate_password_hash

index_bp=Blueprint('index',__name__,url_prefix='/')
auth_bp=Blueprint('auth',__name__,url_prefix='/auth')
task_bp=Blueprint('task',__name__,url_prefix='/task')

@index_bp.route('/',methods=['GET','POST'])
@index_bp.route('/index', methods=['GET','POST'])
@login_required
def index():
    form=TaskForm()
    if form.validate_on_submit():
        task=Task(taskname=form.taskname.data,due_date=form.due_date.data)
        db.session.add(task)
        db.session.commit()

        flash('Task was added.','success')
        return redirect(url_for('index.index'))
    tasks=Task.query.all()
    return render_template('index.html',form=form,tasks=tasks)


@auth_bp.route('/register',methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index.index'))
    form=RegistrationForm()
    if form.validate_on_submit():
        user=User.query.filter_by(username=form.username.data).first()
        if user:
            flash('User already exists','error')
        else:
            if form.password1.data==form.password2.data:
                password=generate_password_hash(form.password1.data)
                user=User(username=form.username.data,password=password)
                db.session.add(user)
                db.session.commit()
                flash('Your account has been created','success')
                return redirect(url_for('auth.login'))
            else:
                flash('Registration failed. Passwords did not match.','error')
    return render_template('register.html',form=form)

@auth_bp.route('/login', methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user=User.query.filter_by(username=form.username.data).first()
        if user and check_password_hash(user.password,form.password.data):
            login_user(user)
            flash('Login has been succeeded.','success')
            return redirect(url_for('index.index'))
        else:
            flash('Login failed.Please check username and password.','error')
    return render_template('login.html',form=form)

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@task_bp.route('/delete/<int:id>', methods=['GET'])
@login_required
def delete_task(id):
    task = Task.query.get_or_404(id)
    db.session.delete(task)
    db.session.commit()
    flash('Task has been deleted.', 'success')
    return redirect(url_for('index.index'))

todoapp/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <title>{% block title %}{% endblock %} - Todo</title>
    <script>
        function hideMsg(targ)
    </script>
</head>
<body>
    <div class="wrap">
        <aside class="sidebar">
            <nav class="globalnav">
            	{% if current_user.is_authenticated %}
                    <p class="welcome">Hello, {{ current_user.username }}</p>
                {% endif %}
          
                <p class="nav_caption">⬛︎ N A V I</p>
                <ul>
                    <li><a href="{{ url_for('index.index') }}">Home</a></li>
                    {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                    {% else %}
                        <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                        <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                    {% endif %}
                </ul>
            </nav>
        </aside>
        <main class="content">
            <article class="items">
                <h2 class="caption">{% block header %}{% endblock %}</h2>
                {% with messages=get_flashed_messages(with_categories=true) %}
                	{% if messages %}
                		{% for category,message in messages %}
	                    <div id="flashmsg"class="{{category}}">
                            <span id="btn">&times;</span>{{ message }}</div>
	                    {% endfor %}
	            	{% endif %}
	            {% endwith %}
                <section class="item">{% block content %}{% endblock %}</section>
            </article>
        </main>
    </div>
    <script>
        document.getElementById('btn').addEventListener('click', () => {
            const flashMsg = document.getElementById('flashmsg');
            if (flashMsg) {
                flashMsg.style.display = 'none';
            }
        });
    </script>
</body>
</html>

todoapp/app/templates/index.html
{% extends 'base.html' %}

{% block title %}YJ's{% endblock %}

{% block header %}ToDo Lists{% endblock %}

{% block content %}
{% if form %}
<form method="post">
	{{ form.hidden_tag() }}
	<table class="t_form">
	<td class="fbody">{{ form.taskname.label }} {{form.taskname}}</td>
	<td class="fbody">{{ form.due_date.label }} {{form.due_date}}</td>
	<td class="fbody">{{ form.submit }}</td>
	</table>
</form>
{% endif %}
<table class="task">
	<tr>
		<th class="t_header">ID</th>
		<th class="t_header">タスク名</th>
		<th class="t_header">作成日時</th>
		<th class="t_header">締切日時</th>
	</tr>
{% for task in tasks %}
	<tr>
		<td class="t_id">{{task.id}}| <a href="{{ url_for('task.delete_task',id=task.id)}}">削除</a></td>
		<td class="t_body">{{task.taskname}}</td>
		<td class="t_body">{{task.created_at.strftime('%Y/%m/%d %H:%M:%S')}}</td>
		<td class="t_body">{{task.due_date.strftime('%Y/%m/%d') }}</td>
	</tr>	
{% endfor %}
</table>
{% endblock %}

todoapp/app/templates/login.html
{% extends 'base.html' %}

{% block title %}Log In{% endblock %}

{% block header %}Log In{% endblock %}

{% block content %}
<form class='auth_form' method="POST">
	{{ form.hidden_tag() }}
	<p>{{ form.username.label }}{{ form.username()}}</p>
	<p>{{ form.password.label }}{{ form.password()}}</p>
	<p>{{ form.submit()}}</p>
</form>
{% endblock %}

todoapp/app/templates/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block header %}Register{% endblock %}

{% block content %}
<form class='auth_form' method="POST">
	{{ form.hidden_tag() }}
	<p>{{ form.username.label }}{{ form.username()}}</p>
	<p>{{ form.password1.label }}{{ form.password1()}}</p>
	<p>{{ form.password2.label }}{{ form.password2()}}</p>
	<p>{{ form.submit()}}</p>
</form>
{% endblock %}

todoapp/app/templates/tasks.html
{% extends 'base.html' %}